-- Seed common measurement types. Idempotent so it can be re-run safely.
INSERT INTO measurement_types (name_en, name_de, abbreviation_en, abbreviation_de) VALUES
    ('teaspoon',    'Teelöffel',     'tsp',     'TL'),
    ('tablespoon',  'Esslöffel',     'tbsp',    'EL'),
    ('fluid ounce', 'Flüssigunze',   'fl oz',   'fl oz'),
    ('cup',         'Tasse',         'cup',     'Tasse'),
    ('milliliter',  'Milliliter',    'ml',      'ml'),
    ('deciliter',   'Deziliter',     'dl',      'dl'),
    ('liter',       'Liter',         'L',       'L'),
    ('quart',       'Quart',         'qt',      'qt'),
    ('gallon',      'Gallone',       'gal',     'gal'),
    ('gram',        'Gramm',         'g',       'g'),
    ('ounce',       'Unze',          'oz',      'oz'),
    ('kilogram',    'Kilogramm',     'kg',      'kg'),
    ('pound',       'Pfund',         'lb',      'Pfd'),
    ('piece',       'Stück',         'pc',      'St'),
    ('slice',       'Scheibe',       'slice',   'Scheibe'),
    ('clove',       'Zehe',          'clove',   'Zehe'),
    ('bunch',       'Bund',          'bunch',   'Bund'),
    ('sprig',       'Zweig',         'sprig',   'Zweig'),
    ('leaf',        'Blatt',         'leaf',    'Blatt'),
    ('pinch',       'Prise',         'pinch',   'Prise'),
    ('dash',        'Spritzer',      'dash',    'Spritzer'),
    ('handful',     'Handvoll',      'handful', 'Handvoll'),
    ('to taste',    'nach Geschmack','to taste','n.G.'),
    ('some',        'etwas',         'some',    'etwas'),
    ('can',         'Dose',          'can',     'Dose'),
    ('package',     'Packung',       'pkg',     'Pkg'),
    ('jar',         'Glas',          'jar',     'Glas'),
    ('bottle',      'Flasche',       'bottle',  'Fl'),
    ('bag',         'Beutel',        'bag',     'Btl'),
    ('box',         'Schachtel',     'box',     'Schachtel')
ON CONFLICT (name_en) DO NOTHING;
